CXX = g++
CXX_FLAGS = -Wall -pedantic -Wextra -g -std=c++14
DIR = build
DEBUG = debug
USERNAME = krejsvoj

HEADERS = $(wildcard src/*.h)
SOURCES = $(wildcard src/*.cpp)
OBJECT_FILES = $(SOURCES:src/%.cpp=$(DIR)/%.o)

.PHONY: all
all: compile doc

.PHONY: run
run: compile
	./$(USERNAME)

.PHONY: compile
compile: $(USERNAME)

.PHONY: doc
doc: Doxyfile $(HEADERS)
	doxygen Doxyfile

.PHONY: clean
clean:
	rm -rf $(DIR)/ $(DEBUG)/ doc/ $(USERNAME) 2>/dev/null

.PHONY: test
test:
	bash tests/test.sh

$(USERNAME): $(DIR)/main
	cp $< $@

$(DIR)/main: $(OBJECT_FILES)
	$(CXX) $(CXX_FLAGS)  $^ -o $@

$(DIR)/%.o: src/%.cpp
	mkdir -p $(DIR)
	$(CXX) $(CXX_FLAGS) $< -c -o $@

$(DEBUG)/test%: tests/test%.cpp $(filter-out build/main.o, $(OBJECT_FILES))
	mkdir -p $(DEBUG)
	$(CXX) $(CXX_FLAGS) $< $(filter-out build/main.o,$(OBJECT_FILES)) -o $@


# Generated by g++ -MM
$(DIR)/CApplication.o: src/CApplication.cpp src/CApplication.h src/CCommand.h \
 src/CGame.h src/CMap.h src/CField.h src/CItem.h src/messages.h \
 src/CCoord.h src/CFieldClay.h src/CFieldBorder.h src/CFieldAir.h \
 src/CFieldLava.h src/CFieldRock.h src/CPlayer.h src/EDirection.h \
 src/CBuffer.h src/CStats.h src/CMyExeptions.h src/CInterface.h \
 src/EColors.h src/CPlayerHuman.h src/CGameCommand.h src/CPlayerMonster.h
$(DIR)/CBuffer.o: src/CBuffer.cpp src/CBuffer.h src/CMap.h src/CField.h \
 src/CItem.h src/messages.h src/CCoord.h src/CFieldClay.h \
 src/CFieldBorder.h src/CFieldAir.h src/CFieldLava.h src/CFieldRock.h \
 src/CStats.h
$(DIR)/CCoord.o: src/CCoord.cpp src/CCoord.h
$(DIR)/CField.o: src/CField.cpp src/CField.h src/CItem.h src/messages.h
$(DIR)/CFieldAir.o: src/CFieldAir.cpp src/CFieldAir.h src/CField.h src/CItem.h \
 src/messages.h
$(DIR)/CFieldBorder.o: src/CFieldBorder.cpp src/CFieldBorder.h src/CField.h \
 src/CItem.h src/messages.h
$(DIR)/CFieldClay.o: src/CFieldClay.cpp src/CFieldClay.h src/CField.h \
 src/CItem.h src/messages.h
$(DIR)/CFieldLava.o: src/CFieldLava.cpp src/CFieldLava.h src/CField.h \
 src/CItem.h src/messages.h
$(DIR)/CFieldRock.o: src/CFieldRock.cpp src/CFieldRock.h src/CField.h \
 src/CItem.h src/messages.h
$(DIR)/CGame.o: src/CGame.cpp src/CGame.h src/CMap.h src/CField.h src/CItem.h \
 src/messages.h src/CCoord.h src/CFieldClay.h src/CFieldBorder.h \
 src/CFieldAir.h src/CFieldLava.h src/CFieldRock.h src/CPlayer.h \
 src/EDirection.h src/CBuffer.h src/CStats.h src/CMyExeptions.h \
 src/CInterface.h src/EColors.h src/CPlayerHuman.h src/CGameCommand.h \
 src/CPlayerMonster.h
$(DIR)/CInterface.o: src/CInterface.cpp src/CInterface.h src/CStats.h \
 src/EColors.h src/CBuffer.h src/CMap.h src/CField.h src/CItem.h \
 src/messages.h src/CCoord.h src/CFieldClay.h src/CFieldBorder.h \
 src/CFieldAir.h src/CFieldLava.h src/CFieldRock.h
$(DIR)/CItem.o: src/CItem.cpp src/CItem.h
$(DIR)/CMap.o: src/CMap.cpp src/CMap.h src/CField.h src/CItem.h src/messages.h \
 src/CCoord.h src/CFieldClay.h src/CFieldBorder.h src/CFieldAir.h \
 src/CFieldLava.h src/CFieldRock.h
$(DIR)/CPlayer.o: src/CPlayer.cpp src/CPlayer.h src/CCoord.h src/CMap.h \
 src/CField.h src/CItem.h src/messages.h src/CFieldClay.h \
 src/CFieldBorder.h src/CFieldAir.h src/CFieldLava.h src/CFieldRock.h \
 src/EDirection.h src/CBuffer.h src/CStats.h src/CMyExeptions.h
$(DIR)/CPlayerHuman.o: src/CPlayerHuman.cpp src/CPlayerHuman.h src/CPlayer.h \
 src/CCoord.h src/CMap.h src/CField.h src/CItem.h src/messages.h \
 src/CFieldClay.h src/CFieldBorder.h src/CFieldAir.h src/CFieldLava.h \
 src/CFieldRock.h src/EDirection.h src/CBuffer.h src/CStats.h \
 src/CMyExeptions.h src/CInterface.h src/EColors.h src/CGameCommand.h
$(DIR)/CPlayerMonster.o: src/CPlayerMonster.cpp src/CPlayerMonster.h \
 src/CPlayer.h src/CCoord.h src/CMap.h src/CField.h src/CItem.h \
 src/messages.h src/CFieldClay.h src/CFieldBorder.h src/CFieldAir.h \
 src/CFieldLava.h src/CFieldRock.h src/EDirection.h src/CBuffer.h \
 src/CStats.h src/CMyExeptions.h
$(DIR)/main.o: src/main.cpp src/CApplication.h src/CCommand.h src/CGame.h \
 src/CMap.h src/CField.h src/CItem.h src/messages.h src/CCoord.h \
 src/CFieldClay.h src/CFieldBorder.h src/CFieldAir.h src/CFieldLava.h \
 src/CFieldRock.h src/CPlayer.h src/EDirection.h src/CBuffer.h \
 src/CStats.h src/CMyExeptions.h src/CInterface.h src/EColors.h \
 src/CPlayerHuman.h src/CGameCommand.h src/CPlayerMonster.h
$(DEBUG)/testCoord.o: tests/testCoord.cpp tests/../src/CCoord.h
$(DEBUG)/testFieldAir.o: tests/testFieldAir.cpp tests/../src/CFieldAir.h \
 tests/../src/CField.h tests/../src/CItem.h tests/../src/messages.h
$(DEBUG)/testFieldBorder.o: tests/testFieldBorder.cpp tests/../src/CFieldBorder.h \
 tests/../src/CField.h tests/../src/CItem.h tests/../src/messages.h
$(DEBUG)/testFieldClay.o: tests/testFieldClay.cpp tests/../src/CFieldClay.h \
 tests/../src/CField.h tests/../src/CItem.h tests/../src/messages.h
$(DEBUG)/testFieldRock.o: tests/testFieldRock.cpp tests/../src/CFieldRock.h \
 tests/../src/CField.h tests/../src/CItem.h tests/../src/messages.h
$(DEBUG)/testFieldLava.o: tests/testFieldLava.cpp tests/../src/CFieldLava.h \
 tests/../src/CField.h tests/../src/CItem.h tests/../src/messages.h
$(DEBUG)/testMap.o: tests/testMap.cpp tests/../src/CMap.h tests/../src/CField.h \
tests/../src/CItem.h tests/../src/messages.h tests/../src/CCoord.h \
tests/../src/CFieldClay.h tests/../src/CFieldBorder.h \
tests/../src/CFieldAir.h tests/../src/CFieldLava.h \
tests/../src/CFieldRock.h
$(DEBUG)/testItem.o: tests/testItem.cpp tests/../src/CItem.h
$(DEBUG)/testPlayerHuman.o: tests/testPlayerHuman.cpp tests/../src/CPlayerHuman.h \
 tests/../src/CPlayer.h tests/../src/CCoord.h tests/../src/CMap.h \
 tests/../src/CField.h tests/../src/CItem.h tests/../src/messages.h \
 tests/../src/CFieldClay.h tests/../src/CFieldBorder.h \
 tests/../src/CFieldAir.h tests/../src/CFieldLava.h \
 tests/../src/CFieldRock.h tests/../src/EDirection.h \
 tests/../src/CBuffer.h tests/../src/CStats.h tests/../src/CMyExeptions.h \
 tests/../src/CInterface.h tests/../src/EColors.h \
 tests/../src/CGameCommand.h
$(DEBUG)/testPlayerMonster.o: tests/testPlayerMonster.cpp \
 tests/../src/CPlayerMonster.h tests/../src/CPlayer.h \
 tests/../src/CCoord.h tests/../src/CMap.h tests/../src/CField.h \
 tests/../src/CItem.h tests/../src/messages.h tests/../src/CFieldClay.h \
 tests/../src/CFieldBorder.h tests/../src/CFieldAir.h \
 tests/../src/CFieldLava.h tests/../src/CFieldRock.h \
 tests/../src/EDirection.h tests/../src/CBuffer.h tests/../src/CStats.h \
 tests/../src/CMyExeptions.h